### ISSUE TITLE
new   FormData()  的append 的方法不生效 ，并且登录请求的没有url 就报以下错误

### ISSUE THREAD

**Issue by GoldenSide** [BluesYoung-web/admin-vue3-element3-vite2#1]
![image](https://user-images.githubusercontent.com/29673579/125279360-711eec80-e346-11eb-8f2a-db08dd673110.png)

**Comment by BluesYoung-web** [comment]
## 没有url先看这个

- https://github.com/BluesYoung-web/admin-vue3-element3-vite2#%E5%89%8D%E7%BD%AE%E6%9D%A1%E4%BB%B6%E6%9C%AC%E5%9C%B0%E8%BF%90%E8%A1%8C

## 至于 FormData

- 不行就换个浏览器吧
